<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Tecnologia;
use Faker\Generator as Faker;

$factory->define(Tecnologia::class, function (Faker $faker) {
    $title = $faker->paragraph(1);
    return [
        'uri' => str_slug($title),
        'titleCourse' => $title,
        'courseDurationFirst' => $faker->paragraph(1),
        'courseDurationSecond' => $faker->paragraph(1),
        'investmentFirst' => $faker->paragraph(1),
        'investmentSecond' => $faker->paragraph(1),
        'workload' => $faker->paragraph(1),
        'workloadDate' => $faker->paragraph(1),
        'titleFirst' => $faker->paragraph(1),
        'titleSecond' => $faker->paragraph(1),
        'titlethird' => $faker->paragraph(1),
        'video' => $faker->paragraph(1),
        'a1First' => $faker->paragraph(1),
        'a1FirstHours' => $faker->paragraph(1),
        'a1Second' => $faker->paragraph(1),
        'a1SecondHours' => $faker->paragraph(1),
        'a1Third' => $faker->paragraph(1),
        'a1ThirdHours' => $faker->paragraph(1),
        'a1Four' => $faker->paragraph(1),
        'a1FourHours' => $faker->paragraph(1),
        'b1First' => $faker->paragraph(1),
        'b1FirstHours' => $faker->paragraph(1),
        'b1Second' => $faker->paragraph(1),
        'b1SecondHours' => $faker->paragraph(1),
        'b1Third' => $faker->paragraph(1),
        'b1ThirdHours' => $faker->paragraph(1),
        'b1Four' => $faker->paragraph(1),
        'b1FourHours' => $faker->paragraph(1),
        'a2First' => $faker->paragraph(1),
        'a2FirstHours' => $faker->paragraph(1),
        'a2Second' => $faker->paragraph(1),
        'a2SecondHours' => $faker->paragraph(1),
        'a2Third' => $faker->paragraph(1),
        'a2ThirdHours' => $faker->paragraph(1),
        'a2Four' => $faker->paragraph(1),
        'a2FourHours' => $faker->paragraph(1),
        'b2First' => $faker->paragraph(1),
        'b2FirstHours' => $faker->paragraph(1),
        'b2Second' => $faker->paragraph(1),
        'b2SecondHours' => $faker->paragraph(1),
        'b2Third' => $faker->paragraph(1),
        'b2ThirdHours' => $faker->paragraph(1),
        'b2Four' => $faker->paragraph(1),
        'b2FourHours' => $faker->paragraph(1),
        'a3First' => $faker->paragraph(1),
        'a3FirstHours' => $faker->paragraph(1),
        'a3Second' => $faker->paragraph(1),
        'a3SecondHours' => $faker->paragraph(1),
        'a3Third' => $faker->paragraph(1),
        'a3ThirdHours' => $faker->paragraph(1),
        'a3Four' => $faker->paragraph(1),
        'a3FourHours' => $faker->paragraph(1),
        'b3First' => $faker->paragraph(1),
        'b3FirstHours' => $faker->paragraph(1),
        'b3Second' => $faker->paragraph(1),
        'b3SecondHours' => $faker->paragraph(1),
        'b3Third' => $faker->paragraph(1),
        'b3ThirdHours' => $faker->paragraph(1),
        'b3Four' => $faker->paragraph(1),
        'b3FourHours' => $faker->paragraph(1),
        'a4First' => $faker->paragraph(1),
        'a4FirstHours' => $faker->paragraph(1),
        'a4Second' => $faker->paragraph(1),
        'a4SecondHours' => $faker->paragraph(1),
        'a4Third' => $faker->paragraph(1),
        'a4ThirdHours' => $faker->paragraph(1),
        'a4Four' => $faker->paragraph(1),
        'a4FourHours' => $faker->paragraph(1),
        'b4First' => $faker->paragraph(1),
        'b4FirstHours' => $faker->paragraph(1),
        'b4Second' => $faker->paragraph(1),
        'b4SecondHours' => $faker->paragraph(1),
        'b4Third' => $faker->paragraph(1),
        'b4ThirdHours' => $faker->paragraph(1),
        'b4Four' => $faker->paragraph(1),
        'b4FourHours' => $faker->paragraph(1),
        'totalFirst' => $faker->paragraph(1),
        'totalsecondHours' => $faker->paragraph(1),
        'courseDescription' => $faker->paragraph(5),
        'courseSubDescription' => $faker->paragraph(5),
        'courseFirst' => $faker->paragraph(2),
        'courseSecond' => $faker->paragraph(2),
        'courseThird' => $faker->paragraph(2),
        'courseBedroom' => $faker->paragraph(2),
        'courseFifth' => $faker->paragraph(2),
        'courseSixth' => $faker->paragraph(2),
        'courseSeventh' => $faker->paragraph(2),
        'courseEighth' => $faker->paragraph(2),
        'courseNinth' => $faker->paragraph(2),
    ];
});
